#!/usr/bin/env sh
set -e
if [ -d /opt/homebrew/opt/ruby/bin ]; then
  export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
elif [ -d /usr/local/opt/ruby/bin ]; then
  export PATH="/usr/local/opt/ruby/bin:$PATH"
fi
cd "$(dirname "$0")/.."
export RUBYOPT="-I${PWD} -r taint_ruby3_shim ${RUBYOPT:-}"
exec bundle exec jekyll build --config _config.yml,_config.dev.yml "$@"
